"""powers table creatd

Revision ID: 92327256f4e8
Revises: ac6b0898ca04
Create Date: 2024-10-07 17:06:28.068246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92327256f4e8'
down_revision = 'ac6b0898ca04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('powers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('powers')
    # ### end Alembic commands ###
